# -*- coding: utf-8 -*-
"""
pdf_generator.py
Generates a professional-grade PDF statistical report following the AP Statistics
"State-Plan-Do-Conclude" framework. Renders LaTeX formulas using Matplotlib.
"""
import io
import datetime
from PIL import Image as PILImage

from reportlab.lib.pagesizes import letter
from reportlab.lib import colors
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, Image as RLImage, KeepTogether, PageBreak
)
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.pdfgen import canvas

# -------------------------------------------------------------------------
# 1. Custom Two-Pass Canvas for Page Numbering and Headers/Footers
# -------------------------------------------------------------------------
class NumberedCanvas(canvas.Canvas):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self._saved_page_states = []

    def showPage(self):
        self._saved_page_states.append(dict(self.__dict__))
        self._startPage()

    def save(self):
        num_pages = len(self._saved_page_states)
        for state in self._saved_page_states:
            self.__dict__.update(state)
            self.draw_page_elements(num_pages)
            canvas.Canvas.showPage(self)
        canvas.Canvas.save(self)

    def draw_page_elements(self, page_count):
        self.saveState()
        self.setFont("Helvetica", 8)
        self.setFillColor(colors.HexColor("#4b5563")) # gray-600
        
        # Header (on pages after the first page)
        if self._pageNumber > 1:
            self.drawString(54, 755, "A/B Testing & Statistical Inference Report")
            self.setStrokeColor(colors.HexColor("#e5e7eb")) # gray-200
            self.setLineWidth(0.5)
            self.line(54, 748, 558, 748)
            
        # Footer (on all pages)
        page_text = f"Page {self._pageNumber} of {page_count}"
        self.drawRightString(558, 40, page_text)
        self.drawString(54, 40, "Confidential | Generated by Python stats-inference-toolkit")
        
        self.setStrokeColor(colors.HexColor("#e5e7eb")) # gray-200
        self.setLineWidth(0.5)
        self.line(54, 50, 558, 50)
        
        self.restoreState()

# -------------------------------------------------------------------------
# 2. LaTeX to ReportLab Flowable Renderer
# -------------------------------------------------------------------------
def latex_to_flowable(latex_str, scale=0.6, dpi=200):
    """
    Renders a LaTeX string into an in-memory transparent PNG using Matplotlib,
    and returns a ReportLab Image flowable. Gracefully falls back to Paragraph
    in case of any failures.
    """
    try:
        import matplotlib
        matplotlib.use('Agg')  # Force non-interactive backend
        import matplotlib.pyplot as plt
        
        # Clean up double backslashes which can happen in raw string transfers
        clean_str = latex_str.replace('\\\\', '\\')
        if not clean_str.startswith('$'):
            clean_str = f"${clean_str}$"
            
        # Render LaTeX into a matplotlib figure
        fig, ax = plt.subplots(figsize=(8, 0.8))
        ax.axis('off')
        
        # Using Helvetica-like sans-serif font for math equations for a modern clean look
        matplotlib.rcParams['mathtext.fontset'] = 'dejavusans'
        
        ax.text(0.5, 0.5, clean_str, fontsize=12, ha='center', va='center', color='#1e3a8a')
        
        buf = io.BytesIO()
        plt.savefig(buf, format='png', dpi=dpi, bbox_inches='tight', transparent=True, pad_inches=0.05)
        plt.close(fig)
        buf.seek(0)
        
        # Get dimensions with Pillow to scale correctly in ReportLab
        img = PILImage.open(buf)
        width, height = img.size
        
        width_pt = (width / dpi) * 72 * scale
        height_pt = (height / dpi) * 72 * scale
        
        buf.seek(0)
        return RLImage(buf, width=width_pt, height=height_pt)
    except Exception as e:
        # Graceful text fallback if matplotlib fails
        styles = getSampleStyleSheet()
        fallback_style = ParagraphStyle(
            'MathFallback',
            parent=styles['Normal'],
            fontName='Helvetica-Oblique',
            fontSize=10,
            textColor=colors.HexColor("#1e3a8a"),
            leftIndent=20
        )
        return Paragraph(f"Formula Fallback: {latex_str}", fallback_style)


def result_chart_to_flowable(test_results, width=420, dpi=180):
    """
    Creates a compact visual summary chart for the PDF report.
    """
    try:
        import matplotlib
        matplotlib.use('Agg')
        import matplotlib.pyplot as plt
        import numpy as np

        test_name = test_results.get("test_name", "")
        group_a_name = test_results.get("group_a_name", "Group A")
        group_b_name = test_results.get("group_b_name", "Group B")
        colors_pair = ["#2563eb", "#0d9488"]

        if "Proportion" in test_name:
            g_a = test_results.get("group_a", {})
            g_b = test_results.get("group_b", {})
            rates = [g_a.get("rate", 0) * 100, g_b.get("rate", 0) * 100]
            ns = [g_a.get("n", 1), g_b.get("n", 1)]
            errors = [
                1.96 * np.sqrt((rate / 100) * (1 - rate / 100) / n) * 100
                for rate, n in zip(rates, ns)
            ]

            fig, ax = plt.subplots(figsize=(6.2, 3.2))
            bars = ax.bar([group_a_name, group_b_name], rates, yerr=errors, capsize=6, color=colors_pair)
            ax.set_title("Conversion Rate by Group with 95% CI", fontsize=11, weight="bold")
            ax.set_ylabel("Conversion rate (%)")
            ax.set_ylim(0, max(5, max([r + e for r, e in zip(rates, errors)]) * 1.25))
            for bar, rate in zip(bars, rates):
                ax.text(bar.get_x() + bar.get_width() / 2, bar.get_height(), f"{rate:.1f}%", ha="center", va="bottom", fontsize=9)

        elif "ANOVA" in test_name:
            summaries = test_results.get("group_summaries", [])
            labels = [summary["name"] for summary in summaries]
            means = [summary["mean"] for summary in summaries]
            stds = [summary["std_dev"] for summary in summaries]
            palette = ["#2563eb", "#0d9488", "#f59e0b", "#ef4444", "#8b5cf6"]

            fig, ax = plt.subplots(figsize=(6.2, 3.2))
            bars = ax.bar(labels, means, yerr=stds, capsize=6, color=palette[:len(labels)])
            ax.set_title("Mean Metric by Group", fontsize=11, weight="bold")
            ax.set_ylabel("Mean value")
            for bar, mean in zip(bars, means):
                ax.text(bar.get_x() + bar.get_width() / 2, bar.get_height(), f"{mean:.2f}", ha="center", va="bottom", fontsize=9)

        elif "T-Test" in test_name:
            g_a = test_results.get("group_a", {})
            g_b = test_results.get("group_b", {})
            means = [g_a.get("mean", 0), g_b.get("mean", 0)]
            stds = [g_a.get("std_dev", 0), g_b.get("std_dev", 0)]

            fig, ax = plt.subplots(figsize=(6.2, 3.2))
            bars = ax.bar([group_a_name, group_b_name], means, yerr=stds, capsize=6, color=colors_pair)
            ax.set_title("Mean Metric by Group", fontsize=11, weight="bold")
            ax.set_ylabel("Mean value")
            for bar, mean in zip(bars, means):
                ax.text(bar.get_x() + bar.get_width() / 2, bar.get_height(), f"{mean:.2f}", ha="center", va="bottom", fontsize=9)

        elif "Mann-Whitney" in test_name:
            g_a = test_results.get("group_a", {})
            g_b = test_results.get("group_b", {})
            medians = [g_a.get("median", 0), g_b.get("median", 0)]

            fig, ax = plt.subplots(figsize=(6.2, 3.2))
            bars = ax.bar([group_a_name, group_b_name], medians, color=colors_pair)
            ax.set_title("Median Metric by Group", fontsize=11, weight="bold")
            ax.set_ylabel("Median value")
            for bar, median in zip(bars, medians):
                ax.text(bar.get_x() + bar.get_width() / 2, bar.get_height(), f"{median:.2f}", ha="center", va="bottom", fontsize=9)

        elif "Chi-Square" in test_name:
            observed = np.asarray(test_results.get("observed", []), dtype=float)
            if observed.size == 0:
                return None
            row_totals = observed.sum(axis=1, keepdims=True)
            row_totals[row_totals == 0] = 1
            pct = observed / row_totals * 100
            labels = test_results.get("group_names", [])
            if len(labels) != pct.shape[0]:
                labels = [group_a_name, group_b_name] if pct.shape[0] == 2 else [f"Group {i+1}" for i in range(pct.shape[0])]

            fig, ax = plt.subplots(figsize=(6.2, 3.2))
            bottoms = np.zeros(pct.shape[0])
            palette = ["#2563eb", "#0d9488", "#f59e0b", "#ef4444", "#8b5cf6"]
            for j in range(pct.shape[1]):
                ax.bar(labels, pct[:, j], bottom=bottoms, color=palette[j % len(palette)], label=f"Category {j+1}")
                bottoms += pct[:, j]
            ax.set_title("Categorical Outcome Distribution by Group", fontsize=11, weight="bold")
            ax.set_ylabel("Percent of responses")
            ax.set_ylim(0, 100)
            ax.legend(loc="upper center", bbox_to_anchor=(0.5, -0.16), ncol=min(3, pct.shape[1]), fontsize=8)

        else:
            return None

        ax.spines["top"].set_visible(False)
        ax.spines["right"].set_visible(False)
        ax.grid(axis="y", alpha=0.18)
        fig.tight_layout()

        buf = io.BytesIO()
        fig.savefig(buf, format="png", dpi=dpi, bbox_inches="tight", facecolor="white")
        plt.close(fig)
        buf.seek(0)

        img = PILImage.open(buf)
        image_width, image_height = img.size
        height = width * image_height / image_width
        buf.seek(0)
        return RLImage(buf, width=width, height=height)
    except Exception:
        return None

# -------------------------------------------------------------------------
# 3. PDF Generator Function
# -------------------------------------------------------------------------
def generate_report(test_results, assumptions_results=None, output_filename="ab_test_report.pdf", metadata=None):
    """
    Orchestrates the creation of the PDF report using the State-Plan-Do-Conclude format.
    """
    # Setup document template with 0.75-inch (54 pt) margins
    doc = SimpleDocTemplate(
        output_filename,
        pagesize=letter,
        leftMargin=54,
        rightMargin=54,
        topMargin=54,
        bottomMargin=54
    )
    
    story = []
    metadata = metadata or {}
    
    # Define Color Palette
    primary_color = colors.HexColor("#1e3a8a")    # Deep Navy
    secondary_color = colors.HexColor("#0d9488")  # Teal
    dark_neutral = colors.HexColor("#1f2937")     # Slate Gray
    light_neutral = colors.HexColor("#f9fafb")    # Off-white
    border_color = colors.HexColor("#e5e7eb")     # Light gray
    accent_green = colors.HexColor("#10b981")     # Emerald Green
    accent_red = colors.HexColor("#ef4444")       # Coral Red

    # Setup Typography Styles
    styles = getSampleStyleSheet()
    
    title_style = ParagraphStyle(
        'ReportTitle', parent=styles['Normal'], fontName='Helvetica-Bold', fontSize=22, leading=26, textColor=primary_color, spaceAfter=8
    )
    subtitle_style = ParagraphStyle(
        'ReportSub', parent=styles['Normal'], fontName='Helvetica', fontSize=10, leading=14, textColor=colors.HexColor("#4b5563"), spaceAfter=18
    )
    h1_style = ParagraphStyle(
        'SectionHeading', parent=styles['Heading1'], fontName='Helvetica-Bold', fontSize=14, leading=18, textColor=primary_color, spaceBefore=12, spaceAfter=8, keepWithNext=True
    )
    h2_style = ParagraphStyle(
        'SubSectionHeading', parent=styles['Heading2'], fontName='Helvetica-Bold', fontSize=11, leading=15, textColor=secondary_color, spaceBefore=8, spaceAfter=4, keepWithNext=True
    )
    body_style = ParagraphStyle(
        'BodyTextCustom', parent=styles['Normal'], fontName='Helvetica', fontSize=10, leading=14, textColor=dark_neutral, spaceAfter=8
    )
    bullet_style = ParagraphStyle(
        'BulletCustom', parent=styles['Normal'], fontName='Helvetica', fontSize=10, leading=14, textColor=dark_neutral, leftIndent=15, spaceAfter=4
    )
    callout_bold_style = ParagraphStyle(
        'CalloutBold', parent=styles['Normal'], fontName='Helvetica-Bold', fontSize=10, leading=14, textColor=primary_color
    )
    callout_body_style = ParagraphStyle(
        'CalloutBody', parent=styles['Normal'], fontName='Helvetica', fontSize=9.5, leading=13.5, textColor=dark_neutral
    )
    exec_label_style = ParagraphStyle(
        'ExecLabel', parent=styles['Normal'], fontName='Helvetica-Bold', fontSize=9.5, leading=13, textColor=colors.white
    )
    exec_body_style = ParagraphStyle(
        'ExecBody', parent=styles['Normal'], fontName='Helvetica', fontSize=9.5, leading=13, textColor=dark_neutral
    )

    # Helper function for drawing horizontal rules
    def get_divider():
        t = Table([[""]], colWidths=[504], rowHeights=[2])
        t.setStyle(TableStyle([
            ('BACKGROUND', (0,0), (-1,-1), primary_color),
            ('BOTTOMPADDING', (0,0), (-1,-1), 0),
            ('TOPPADDING', (0,0), (-1,-1), 0),
        ]))
        return t

    # Helper function for Callout Boxes
    def make_callout(bold_text, text, bg_color="#f0f9ff", border_color="#bae6fd"):
        content = [
            Paragraph(bold_text, callout_bold_style),
            Spacer(1, 4),
            Paragraph(text, callout_body_style)
        ]
        t = Table([[content]], colWidths=[504])
        t.setStyle(TableStyle([
            ('BACKGROUND', (0,0), (-1,-1), colors.HexColor(bg_color)),
            ('BOX', (0,0), (-1,-1), 1, colors.HexColor(border_color)),
            ('TOPPADDING', (0,0), (-1,-1), 8),
            ('BOTTOMPADDING', (0,0), (-1,-1), 8),
            ('LEFTPADDING', (0,0), (-1,-1), 12),
            ('RIGHTPADDING', (0,0), (-1,-1), 12),
        ]))
        return t

    def get_group_labels():
        return (
            test_results.get("group_a_name", "Group A"),
            test_results.get("group_b_name", "Group B"),
        )

    def p_value_text(p_value):
        if p_value < 0.0001:
            return f"{p_value:.2e}"
        return f"{p_value:.4f}"

    def build_plain_english_summary():
        group_a_label, group_b_label = get_group_labels()
        test_name = test_results.get("test_name", "statistical test")
        p_val = test_results.get("p_value", 1.0)
        alpha = test_results.get("alpha", 0.05)
        diff = test_results.get("difference", 0.0)
        reject = test_results.get("reject_h0", False)

        direction = ""
        if isinstance(diff, (int, float)):
            if diff > 0:
                direction = f" {group_b_label} was higher than {group_a_label} in this sample."
            elif diff < 0:
                direction = f" {group_b_label} was lower than {group_a_label} in this sample."

        if reject:
            return (
                f"The {test_name} found a statistically significant result "
                f"(p = {p_value_text(p_val)}, alpha = {alpha}).{direction}"
            )

        return (
            f"The {test_name} did not find a statistically significant result "
            f"(p = {p_value_text(p_val)}, alpha = {alpha}).{direction} "
            "The observed difference may be random noise."
        )

    def build_recommendation():
        test_name = test_results.get("test_name", "")
        diff = test_results.get("difference", 0.0)
        reject = test_results.get("reject_h0", False)
        group_a_label, group_b_label = get_group_labels()

        if "Proportion" in test_name:
            if reject:
                better_group = group_b_label if diff > 0 else group_a_label
                return f"Use {better_group} if the business goal is to maximize conversion rate."
            return "Do not roll out the variant based on current evidence; collect more data or keep the control."

        if "ANOVA" in test_name:
            if reject:
                summaries = test_results.get("group_summaries", [])
                best = max(summaries, key=lambda item: item["mean"]) if summaries else None
                return f"Group means differ significantly; review Tukey post-hoc results. Highest observed mean: {best['name']}." if best else "Group means differ significantly; review Tukey post-hoc results."
            return "No statistically significant difference was detected across group means."

        if "T-Test" in test_name or "Mann-Whitney" in test_name:
            if reject:
                better_group = group_b_label if diff > 0 else group_a_label
                return f"Use {better_group} if a higher metric value is better for the business objective."
            return "Treat both groups as statistically similar; choose based on cost, UX, or operational simplicity."

        if reject:
            return "Segment-level behavior differs across groups; review category patterns before standardizing the offer."
        return "No reliable association was detected; a standardized offer or layout is reasonable."

    def build_confidence_text():
        if "ci_lower" in test_results and "ci_upper" in test_results:
            level = (1 - test_results.get("alpha", 0.05)) * 100
            return (
                f"{level:.0f}% CI for Group B - Group A: "
                f"[{test_results['ci_lower']:.4f}, {test_results['ci_upper']:.4f}]"
            )
        if "degrees_of_freedom" in test_results:
            return f"Degrees of freedom: {test_results.get('degrees_of_freedom')}"
        return "See detailed statistical output in the Do section."

    def make_executive_summary():
        p_val = test_results.get("p_value", 1.0)
        alpha = test_results.get("alpha", 0.05)
        reject = test_results.get("reject_h0", False)
        result_line = (
            "A statistically significant difference was detected."
            if reject else
            "No statistically significant difference was detected."
        )
        rows = [
            [Paragraph("TEST", exec_label_style), Paragraph(test_results.get("test_name", "N/A"), exec_body_style)],
            [Paragraph("RESULT", exec_label_style), Paragraph(f"{result_line} p = {p_value_text(p_val)} at alpha = {alpha}.", exec_body_style)],
            [Paragraph("RECOMMENDATION", exec_label_style), Paragraph(build_recommendation(), exec_body_style)],
            [Paragraph("CONFIDENCE", exec_label_style), Paragraph(build_confidence_text(), exec_body_style)],
            [Paragraph("PLAIN ENGLISH", exec_label_style), Paragraph(build_plain_english_summary(), exec_body_style)],
        ]
        table = Table(rows, colWidths=[122, 382])
        table.setStyle(TableStyle([
            ('BACKGROUND', (0,0), (0,-1), primary_color),
            ('BACKGROUND', (1,0), (1,-1), colors.HexColor("#f8fafc")),
            ('BOX', (0,0), (-1,-1), 1, border_color),
            ('INNERGRID', (0,0), (-1,-1), 0.5, border_color),
            ('TOPPADDING', (0,0), (-1,-1), 8),
            ('BOTTOMPADDING', (0,0), (-1,-1), 8),
            ('LEFTPADDING', (0,0), (-1,-1), 10),
            ('RIGHTPADDING', (0,0), (-1,-1), 10),
            ('VALIGN', (0,0), (-1,-1), 'TOP'),
        ]))
        return table

    def build_expected_lift_text():
        test_name = test_results.get("test_name", "")
        diff = test_results.get("difference", 0.0)
        if "Proportion" in test_name:
            return f"Observed lift: {diff:+.2%} conversion-rate points for {group_b_label} vs {group_a_label}."
        if "T-Test" in test_name or "Mann-Whitney" in test_name:
            return f"Observed difference: {diff:+.4f} metric units for {group_b_label} vs {group_a_label}."
        if "ANOVA" in test_name:
            summaries = test_results.get("group_summaries", [])
            if summaries:
                best = max(summaries, key=lambda item: item["mean"])
                worst = min(summaries, key=lambda item: item["mean"])
                return f"Observed range: {best['name']} is {best['mean'] - worst['mean']:+.4f} units above {worst['name']}."
        return "See distribution chart for the observed group difference."

    def make_business_takeaway():
        reject = test_results.get("reject_h0", False)
        p_val = test_results.get("p_value", 1.0)
        if reject:
            title = "Recommendation: Act on the result, with business context"
            text = (
                f"{build_recommendation()} The result is statistically reliable at the selected threshold "
                f"(p = {p_value_text(p_val)}), but business impact should still be weighed against launch cost, risk, and sample quality."
            )
            return make_callout(title, text, bg_color="#ecfdf5", border_color="#a7f3d0")
        title = "Recommendation: Do not roll out based on this result alone"
        text = (
            f"{build_recommendation()} The current evidence is not strong enough to treat the observed difference "
            f"as a reliable business improvement (p = {p_value_text(p_val)})."
        )
        return make_callout(title, text, bg_color="#f8fafc", border_color="#cbd5e1")

    def make_business_metrics_table():
        rows = [
            ["Question", "Answer"],
            ["Should we roll it out?", build_recommendation()],
            ["Expected lift / difference", build_expected_lift_text()],
            ["Statistical confidence", build_confidence_text()],
            ["Effect size", f"{test_results.get('effect_size_label', 'Effect size')}: {test_results.get('effect_size_value', 0.0):.4f}"],
            ["Plain-English result", build_plain_english_summary()],
        ]
        table = Table(rows, colWidths=[150, 354])
        table.setStyle(TableStyle([
            ('BACKGROUND', (0,0), (-1,0), primary_color),
            ('TEXTCOLOR', (0,0), (-1,0), colors.white),
            ('ALIGN', (0,0), (-1,-1), 'LEFT'),
            ('VALIGN', (0,0), (-1,-1), 'TOP'),
            ('BOTTOMPADDING', (0,0), (-1,-1), 7),
            ('TOPPADDING', (0,0), (-1,-1), 7),
            ('GRID', (0,0), (-1,-1), 0.5, border_color),
            ('ROWBACKGROUNDS', (0,1), (-1,-1), [colors.white, light_neutral]),
        ]))
        return table

    def append_methods_appendix():
        story.append(PageBreak())
        story.append(Paragraph("Methods Appendix", h1_style))
        story.append(Paragraph("Kept concise for buyer review. Full statistical details are available in the researcher / PhD audience version.", body_style))
        rows = [
            ["Test selected", test_results.get("test_name", "N/A")],
            ["p-value", p_value_text(test_results.get("p_value", 1.0))],
            ["Effect size", f"{test_results.get('effect_size_label', 'Effect size')}: {test_results.get('effect_size_value', 0.0):.4f}"],
            ["Confidence / df", build_confidence_text()],
        ]
        table = Table(rows, colWidths=[150, 354])
        table.setStyle(TableStyle([
            ('BACKGROUND', (0,0), (0,-1), colors.HexColor("#eef2ff")),
            ('GRID', (0,0), (-1,-1), 0.5, border_color),
            ('VALIGN', (0,0), (-1,-1), 'TOP'),
            ('TOPPADDING', (0,0), (-1,-1), 7),
            ('BOTTOMPADDING', (0,0), (-1,-1), 7),
        ]))
        story.append(table)

    def build_short_report(report_style):
        story.append(Paragraph("What This Means", h1_style))
        story.append(make_business_takeaway())
        story.append(Spacer(1, 12))
        story.append(Paragraph("Decision Snapshot", h1_style))
        story.append(make_business_metrics_table())
        story.append(Spacer(1, 12))

        chart_flowable = result_chart_to_flowable(test_results)
        if chart_flowable:
            story.append(Paragraph("Visual Result", h1_style))
            story.append(chart_flowable)
            story.append(Spacer(1, 10))

        story.append(Paragraph("Suggested Next Step", h1_style))
        if test_results.get("reject_h0"):
            next_step = "If the business cost is acceptable, run a controlled rollout or confirm with one follow-up test before a full launch."
        else:
            next_step = "Keep the current version, collect more data, or test a stronger change before rollout."
        story.append(Paragraph(next_step, body_style))

        if report_style == "fiverr":
            story.append(Spacer(1, 10))
            story.append(make_callout(
                "Need the next version?",
                "This report can be expanded into a Streamlit mini-dashboard, multi-metric analysis, or a short interpretation call.",
                bg_color="#f0fdfa",
                border_color="#99f6e4",
            ))
        else:
            append_methods_appendix()

    # -------------------------------------------------------------------------
    # Title Block
    # -------------------------------------------------------------------------
    audience = metadata.get("audience", "researcher")
    audience_to_style = {
        "fiverr_buyer": "fiverr",
        "small_business": "business",
        "researcher": "research",
    }
    report_style = audience_to_style.get(audience, "research")
    report_titles = {
        "business": "A/B Test Business Decision Report",
        "fiverr": "A/B Test Client Summary",
        "research": "Client Statistical Analysis Report",
    }
    story.append(Paragraph(report_titles.get(report_style, report_titles["research"]), title_style))
    date_str = datetime.date.today().strftime("%B %d, %Y")
    client_name = metadata.get("client_name") or "Portfolio Demo / Custom CSV Project"
    prepared_by = metadata.get("prepared_by") or "Tianyou Liu - Statistical Analysis"
    story.append(Paragraph(f"<b>Client:</b> {client_name} | <b>Prepared by:</b> {prepared_by} | <b>Date:</b> {date_str}", subtitle_style))
    story.append(get_divider())
    story.append(Spacer(1, 15))

    test_name = test_results.get("test_name", "")
    group_a_label, group_b_label = get_group_labels()

    # -------------------------------------------------------------------------
    # EXECUTIVE SUMMARY
    # -------------------------------------------------------------------------
    story.append(Paragraph("Executive Summary", h1_style))
    story.append(Paragraph("High-level decision summary for business stakeholders before the full statistical methodology.", body_style))
    story.append(make_executive_summary())
    story.append(Spacer(1, 14))

    if report_style in {"business", "fiverr"}:
        build_short_report(report_style)
        doc.build(story, canvasmaker=NumberedCanvas)
        return

    # -------------------------------------------------------------------------
    # PART 1: STATE
    # -------------------------------------------------------------------------
    story.append(Paragraph("1. State", h1_style))
    story.append(Paragraph("Define the hypotheses and significance level to evaluate the claims of the A/B test.", body_style))
    
    formulas = test_results.get("formulas", {})
    
    # Create hypothesis info
    h_latex = formulas.get("hypothesis", "")
    hyp_img = latex_to_flowable(h_latex)
    
    story.append(Paragraph(f"<b>Significance Level (&alpha;):</b> {test_results.get('alpha', 0.05)}", body_style))
    story.append(Paragraph("<b>Hypotheses (Symbols):</b>", body_style))
    story.append(hyp_img)
    story.append(Spacer(1, 6))
    
    # Hypothesis in words
    if "Proportion" in test_name:
        words = f"<b>Null Hypothesis (H<sub>0</sub>):</b> There is no difference in the conversion rates between {group_a_label} and {group_b_label} (p<sub>A</sub> = p<sub>B</sub>).<br/>" \
                f"<b>Alternative Hypothesis (H<sub>a</sub>):</b> There is a statistically significant difference in the conversion rates between {group_a_label} and {group_b_label} (p<sub>A</sub> &ne; p<sub>B</sub>)."
    elif "T-Test" in test_name:
        words = f"<b>Null Hypothesis (H<sub>0</sub>):</b> There is no difference in the means of the metrics between {group_a_label} and {group_b_label} (&mu;<sub>A</sub> = &mu;<sub>B</sub>).<br/>" \
                f"<b>Alternative Hypothesis (H<sub>a</sub>):</b> There is a statistically significant difference in the means of the metrics between {group_a_label} and {group_b_label} (&mu;<sub>A</sub> &ne; &mu;<sub>B</sub>)."
    elif "ANOVA" in test_name:
        words = "<b>Null Hypothesis (H<sub>0</sub>):</b> All group means are equal.<br/>" \
                "<b>Alternative Hypothesis (H<sub>a</sub>):</b> At least one group mean is significantly different."
    elif "Chi-Square" in test_name:
        words = "<b>Null Hypothesis (H<sub>0</sub>):</b> The categorical variables are independent; the distribution of responses is similar across groups.<br/>" \
                "<b>Alternative Hypothesis (H<sub>a</sub>):</b> The categorical variables are dependent; the distribution of responses is significantly different across groups."
    else:
        words = "<b>Null Hypothesis (H<sub>0</sub>):</b> The distributions of both groups are identical.<br/>" \
                "<b>Alternative Hypothesis (H<sub>a</sub>):</b> There is a systematic difference in values between the two groups."
                
    story.append(Paragraph(words, body_style))
    story.append(Spacer(1, 12))

    # -------------------------------------------------------------------------
    # PART 2: PLAN
    # -------------------------------------------------------------------------
    story.append(Paragraph("2. Plan", h1_style))
    story.append(Paragraph(f"Identify the appropriate statistical procedure and verify its mathematical assumptions.", body_style))
    story.append(Paragraph(f"<b>Recommended Procedure:</b> {test_results.get('test_name')}", body_style))
    
    # Determine assumptions & check conditions
    conditions_summary = []
    conditions_met = True
    
    if "Proportion" in test_name:
        # Success-Failure condition check
        g_a = test_results.get("group_a", {})
        g_b = test_results.get("group_b", {})
        
        suc_a, n_a = g_a.get("successes", 0), g_a.get("n", 1)
        suc_b, n_b = g_b.get("successes", 0), g_b.get("n", 1)
        fail_a = n_a - suc_a
        fail_b = n_b - suc_b
        
        cond_a_ok = (suc_a >= 10) and (fail_a >= 10)
        cond_b_ok = (suc_b >= 10) and (fail_b >= 10)
        
        sf_text = f"Group A successes ({suc_a}) & failures ({fail_a}) &ge; 10? {'<b>Yes</b>' if cond_a_ok else '<b>No</b>'}. " \
                  f"Group B successes ({suc_b}) & failures ({fail_b}) &ge; 10? {'<b>Yes</b>' if cond_b_ok else '<b>No</b>'}."
        
        conditions_summary.append(("Randomness", "Assuming samples are collected via independent random selection."))
        conditions_summary.append(("Independence", "Samples represent less than 10% of their respective target populations."))
        conditions_summary.append(("Success-Failure Condition", sf_text))
        
        conditions_met = cond_a_ok and cond_b_ok
        
    elif "T-Test" in test_name or "Mann-Whitney" in test_name:
        # Normality and variance diagnostics
        conditions_summary.append(("Randomness", "Assuming independent random sampling/assignment of groups."))
        conditions_summary.append(("Independence", "Samples are mutually independent and represent < 10% of population."))
        
        if assumptions_results:
            norm_a = assumptions_results["group_a_normality"]
            norm_b = assumptions_results["group_b_normality"]
            homo = assumptions_results["variance_equality"]
            
            norm_text = f"Group A Normality (p = {norm_a['p_value']:.4f}, {'Passed' if norm_a['shapiro_normal'] else 'Failed'}). " \
                        f"Group B Normality (p = {norm_b['p_value']:.4f}, {'Passed' if norm_b['shapiro_normal'] else 'Failed'})."
            
            if norm_a["normal"] and norm_b["normal"]:
                norm_text += " Normality met."
            else:
                norm_text += " Normality met via CLT (Sample sizes >= 30)." if (norm_a["normal"] and norm_b["normal"]) else " Normality assumptions NOT fully met."
                
            conditions_summary.append(("Normality (Shapiro-Wilk)", norm_text))
            
            var_text = f"Levene's Test for equal variance: p = {homo['p_value']:.4f} ({'Equal variances assumed' if homo['equal_var'] else 'Unequal variances assumed'})."
            conditions_summary.append(("Equal Variance (Levene's)", var_text))
            
            conditions_met = norm_a["normal"] and norm_b["normal"]
        else:
            conditions_summary.append(("Normality check", "Shapiro-Wilk normality diagnostics skipped."))
            conditions_summary.append(("Variance check", "Levene's homogeneity diagnostics skipped."))
    elif "ANOVA" in test_name:
        conditions_summary.append(("Randomness", "Assuming independent random sampling/assignment of groups."))
        conditions_summary.append(("Independence", "Observations are independent within and across groups."))
        conditions_summary.append(("Normality", "For portfolio demo purposes, ANOVA is applied to compare 3+ numeric group means. Review residual diagnostics for formal research delivery."))
        conditions_summary.append(("Post-hoc Testing", "Tukey HSD pairwise comparisons are included when statsmodels is available."))
            
    elif "Chi-Square" in test_name:
        conditions_summary.append(("Randomness", "Categorical frequencies collected from random sampling."))
        conditions_summary.append(("Independence", "Observations represent mutually exclusive categorical responses."))
        
        # Expected Cell Counts check (all expected counts >= 5)
        expected = test_results.get("expected", [])
        expected_flat = [val for row in expected for val in row]
        exp_ok = all(val >= 5 for val in expected_flat)
        min_exp = min(expected_flat) if expected_flat else 0
        
        ec_text = f"All expected cell counts &ge; 5? {'<b>Yes</b>' if exp_ok else '<b>No</b>'} (Minimum expected cell count = {min_exp:.2f})."
        conditions_summary.append(("Large Sample (Expected counts)", ec_text))
        
        conditions_met = exp_ok

    # Build standard table of conditions
    cond_data = [["Assumption / Condition Checked", "Status & Diagnostic Details"]]
    for title, detail in conditions_summary:
        cond_data.append([
            Paragraph(f"<b>{title}</b>", body_style),
            Paragraph(detail, body_style)
        ])
        
    cond_table = Table(cond_data, colWidths=[150, 354])
    cond_table.setStyle(TableStyle([
        ('BACKGROUND', (0,0), (-1,0), secondary_color),
        ('TEXTCOLOR', (0,0), (-1,0), colors.white),
        ('ALIGN', (0,0), (-1,-1), 'LEFT'),
        ('BOTTOMPADDING', (0,0), (-1,-1), 6),
        ('TOPPADDING', (0,0), (-1,-1), 6),
        ('GRID', (0,0), (-1,-1), 0.5, border_color),
        ('BACKGROUND', (0,1), (-1,-1), light_neutral),
    ]))
    
    story.append(cond_table)
    story.append(Spacer(1, 8))
    
    # Diagnostic Callout Box
    if conditions_met:
        story.append(make_callout(
            " CONDITIONS MET",
            f"All mathematical conditions for the {test_name} are satisfied. Parametric results are highly reliable.",
            bg_color="#ecfdf5", border_color="#a7f3d0"
        ))
    else:
        rec_test = assumptions_results.get("recommended_test", "Non-parametric alternative") if assumptions_results else "a non-parametric test"
        story.append(make_callout(
            " ASSUMPTION VIOLATION ENCOUNTERED",
            f"Some statistical conditions are violated. The tool automatically routed/recommends using {rec_test} to ensure robust inference.",
            bg_color="#fffbef", border_color="#fef3c7"
        ))
    story.append(Spacer(1, 12))

    # -------------------------------------------------------------------------
    # PART 3: DO
    # -------------------------------------------------------------------------
    story.append(Paragraph("3. Do", h1_style))
    story.append(Paragraph("Calculate sample metrics, standard error, test statistic, and the resulting p-value.", body_style))
    
    # Summary stats table
    story.append(Paragraph("<b>Sample Descriptive Statistics:</b>", h2_style))
    
    if "Proportion" in test_name:
        stats_data = [
            ["Group", "Sample Size (n)", "Successes (x)", "Conversion Rate (p̂)"],
            [group_a_label, f"{g_a['n']}", f"{g_a['successes']}", f"{g_a['rate']:.4%}"],
            [group_b_label, f"{g_b['n']}", f"{g_b['successes']}", f"{g_b['rate']:.4%}"]
        ]
        stats_table = Table(stats_data, colWidths=[120, 128, 128, 128])
    elif "T-Test" in test_name:
        g_a = test_results.get("group_a", {})
        g_b = test_results.get("group_b", {})
        stats_data = [
            ["Group", "Sample Size (n)", "Sample Mean (x̄)", "Standard Deviation (s)", "Variance (s²)"],
            [group_a_label, f"{g_a['n']}", f"{g_a['mean']:.4f}", f"{g_a['std_dev']:.4f}", f"{g_a['variance']:.4f}"],
            [group_b_label, f"{g_b['n']}", f"{g_b['mean']:.4f}", f"{g_b['std_dev']:.4f}", f"{g_b['variance']:.4f}"]
        ]
        stats_table = Table(stats_data, colWidths=[100, 101, 101, 101, 101])
    elif "ANOVA" in test_name:
        summaries = test_results.get("group_summaries", [])
        stats_data = [["Group", "Sample Size (n)", "Sample Mean (x̄)", "Standard Deviation (s)", "Variance (s²)"]]
        for summary in summaries:
            stats_data.append([
                summary["name"],
                f"{summary['n']}",
                f"{summary['mean']:.4f}",
                f"{summary['std_dev']:.4f}",
                f"{summary['variance']:.4f}",
            ])
        stats_table = Table(stats_data, colWidths=[100, 101, 101, 101, 101])
    elif "Chi-Square" in test_name:
        obs = test_results.get("observed", [])
        exp = test_results.get("expected", [])
        
        # Build flat observed vs expected metrics table
        stats_data = [["Cell Index (Row, Col)", "Observed Count (O)", "Expected Count (E)", "Residual Contribution (O-E)²/E"]]
        for i in range(len(obs)):
            for j in range(len(obs[i])):
                o_val = obs[i][j]
                e_val = exp[i][j]
                contrib = ((o_val - e_val)**2 / e_val) if e_val > 0 else 0
                stats_data.append([
                    f"Row {i+1}, Col {j+1}",
                    f"{o_val}",
                    f"{e_val:.2f}",
                    f"{contrib:.4f}"
                ])
        stats_table = Table(stats_data, colWidths=[150, 118, 118, 118])
    else: # Mann-Whitney
        g_a = test_results.get("group_a", {})
        g_b = test_results.get("group_b", {})
        stats_data = [
            ["Group", "Sample Size (n)", "Median Value"],
            [group_a_label, f"{g_a['n']}", f"{g_a['median']:.4f}"],
            [group_b_label, f"{g_b['n']}", f"{g_b['median']:.4f}"]
        ]
        stats_table = Table(stats_data, colWidths=[150, 177, 177])

    stats_table.setStyle(TableStyle([
        ('BACKGROUND', (0,0), (-1,0), primary_color),
        ('TEXTCOLOR', (0,0), (-1,0), colors.white),
        ('ALIGN', (0,0), (-1,-1), 'CENTER'),
        ('BOTTOMPADDING', (0,0), (-1,-1), 5),
        ('TOPPADDING', (0,0), (-1,-1), 5),
        ('GRID', (0,0), (-1,-1), 0.5, border_color),
        ('ROWBACKGROUNDS', (0,1), (-1,-1), [colors.white, light_neutral]),
    ]))
    
    story.append(stats_table)
    story.append(Spacer(1, 10))

    chart_flowable = result_chart_to_flowable(test_results)
    if chart_flowable:
        story.append(Paragraph("<b>Visual Summary:</b>", h2_style))
        story.append(chart_flowable)
        story.append(Spacer(1, 10))
    
    # Math Calculations & Formulas
    story.append(Paragraph("<b>Calculations & Mathematical Formulations:</b>", h2_style))
    
    # Add step-by-step formula images
    for name, f_str in formulas.items():
        if name != "hypothesis":
            story.append(Paragraph(f"• <i>{name.replace('_', ' ').title()}</i>:", body_style))
            story.append(latex_to_flowable(f_str))
            story.append(Spacer(1, 4))
            
    story.append(Spacer(1, 6))

    # Core statistics results table
    res_data = [
        ["Statistical Parameter", "Value"],
        [f"Test Statistic ({'Z' if 'Z-Test' in test_name else 't' if 'T-Test' in test_name else 'F' if 'ANOVA' in test_name else 'U' if 'Mann-Whitney' in test_name else 'χ²'})", f"{test_results.get('statistic', 0.0):.5f}"],
        ["p-value", f"{test_results.get('p_value', 1.0):.5e}" if test_results.get('p_value', 1.0) < 0.0001 else f"{test_results.get('p_value', 1.0):.5f}"]
    ]
    
    if "degrees_of_freedom" in test_results:
        res_data.append(["Degrees of Freedom (df)", f"{test_results.get('degrees_of_freedom'):.2f}" if isinstance(test_results.get('degrees_of_freedom'), float) else f"{test_results.get('degrees_of_freedom')}"])
        
    if "ci_lower" in test_results:
        ci_text = f"({test_results.get('ci_lower'):.4f}, {test_results.get('ci_upper'):.4f})"
        res_data.append([f"{(1-test_results.get('alpha', 0.05))*100:.0f}% Confidence Interval", ci_text])

    if "effect_size_value" in test_results:
        effect_label = test_results.get("effect_size_label", "Effect Size")
        effect_value = test_results.get("effect_size_value")
        effect_text = f"{effect_value:.4f}"
        if test_results.get("effect_size_note"):
            effect_text += f" ({test_results.get('effect_size_note')})"
        res_data.append([effect_label, effect_text])
        
    res_table = Table(res_data, colWidths=[250, 254])
    res_table.setStyle(TableStyle([
        ('BACKGROUND', (0,0), (-1,0), secondary_color),
        ('TEXTCOLOR', (0,0), (-1,0), colors.white),
        ('ALIGN', (0,0), (0,-1), 'LEFT'),
        ('ALIGN', (1,0), (1,-1), 'RIGHT'),
        ('BOTTOMPADDING', (0,0), (-1,-1), 5),
        ('TOPPADDING', (0,0), (-1,-1), 5),
        ('GRID', (0,0), (-1,-1), 0.5, border_color),
        ('BACKGROUND', (0,1), (-1,-1), light_neutral),
    ]))
    
    story.append(res_table)
    story.append(Spacer(1, 15))

    if test_results.get("post_hoc"):
        story.append(Paragraph("<b>Post-hoc Pairwise Comparisons:</b>", h2_style))
        tukey_data = [["Group 1", "Group 2", "Mean Diff", "p-adj", "95% CI", "Reject H0"]]
        for row in test_results["post_hoc"]:
            tukey_data.append([
                row["group1"],
                row["group2"],
                f"{row['mean_diff']:.4f}",
                f"{row['p_adj']:.4f}",
                f"[{row['lower']:.4f}, {row['upper']:.4f}]",
                "Yes" if row["reject"] else "No",
            ])
        tukey_table = Table(tukey_data, colWidths=[78, 78, 78, 78, 116, 76])
        tukey_table.setStyle(TableStyle([
            ('BACKGROUND', (0,0), (-1,0), primary_color),
            ('TEXTCOLOR', (0,0), (-1,0), colors.white),
            ('ALIGN', (0,0), (-1,-1), 'CENTER'),
            ('BOTTOMPADDING', (0,0), (-1,-1), 5),
            ('TOPPADDING', (0,0), (-1,-1), 5),
            ('GRID', (0,0), (-1,-1), 0.5, border_color),
            ('ROWBACKGROUNDS', (0,1), (-1,-1), [colors.white, light_neutral]),
        ]))
        story.append(tukey_table)
        story.append(Spacer(1, 12))

    # -------------------------------------------------------------------------
    # PART 4: CONCLUDE
    # -------------------------------------------------------------------------
    story.append(Paragraph("4. Conclude", h1_style))
    story.append(Paragraph("State the final decision and offer a business interpretation based on the statistical results.", body_style))
    
    p_val = test_results.get("p_value", 1.0)
    alpha = test_results.get("alpha", 0.05)
    reject = test_results.get("reject_h0", False)
    
    decision_text = f"Compare p-value to &alpha;: {p_val:.5f} {'<' if reject else '>='} {alpha}. "
    if reject:
        decision_text += "Since the p-value is less than the significance level, we <b>reject the null hypothesis (H<sub>0</sub>)</b>. " \
                         "There is strong evidence supporting a statistically significant difference between the two variations."
        conclude_box_title = " DECISION: REJECT NULL HYPOTHESIS"
        conclude_box_color = "#fef2f2" # Light Red
        conclude_box_border = "#fecaca"
    else:
        decision_text += "Since the p-value is greater than or equal to the significance level, we <b>fail to reject the null hypothesis (H<sub>0</sub>)</b>. " \
                         "There is insufficient evidence to conclude there is a significant difference between the variations."
        conclude_box_title = " DECISION: FAIL TO REJECT NULL HYPOTHESIS"
        conclude_box_color = "#f3f4f6" # Light Gray
        conclude_box_border = "#e5e7eb"

    # Business impact description
    if "Proportion" in test_name:
        diff_rate = test_results.get("difference", 0.0)
        if reject:
            better_group = "Group B" if diff_rate > 0 else "Group A"
            impact_text = f"<b>Business Action Recommendation:</b> The conversion rate difference of {abs(diff_rate):.2%} is statistically significant. " \
                          f"Deploy <b>{better_group}</b> to production, as it is expected to generate a permanent uplift in performance."
        else:
            impact_text = "<b>Business Action Recommendation:</b> The observed difference in conversion rates could be due to random chance. " \
                          "Maintain the current control group (Group A) or extend the experiment to gather more data before implementing changes."
    elif "ANOVA" in test_name:
        if reject:
            summaries = test_results.get("group_summaries", [])
            best = max(summaries, key=lambda item: item["mean"]) if summaries else None
            best_text = f" <b>{best['name']}</b> has the highest observed mean." if best else ""
            impact_text = "<b>Business Action Recommendation:</b> At least one group mean differs significantly. " \
                          "Review Tukey post-hoc comparisons to identify which variants differ." + best_text
        else:
            impact_text = "<b>Business Action Recommendation:</b> No statistically significant mean difference was detected across groups. " \
                          "Choose based on implementation cost, UX, or operational simplicity."
    elif "T-Test" in test_name or "Mann-Whitney" in test_name:
        diff_mean = test_results.get("difference", 0.0)
        if reject:
            better_group = "Group B" if diff_mean > 0 else "Group A"
            impact_text = f"<b>Business Action Recommendation:</b> The metric difference of {diff_mean:.4f} is statistically significant. " \
                          f"Variation <b>{better_group}</b> outperforms the other and should be adopted to maximize efficiency/revenue."
        else:
            impact_text = "<b>Business Action Recommendation:</b> There is no statistically detectable difference in performance. " \
                          "The variations perform identically on average. We recommend choosing the option that has lower maintenance costs or better UX."
    else:
        if reject:
            impact_text = "<b>Business Action Recommendation:</b> The frequencies are dependent. A significant association exists. " \
                          "The user segments show distinct preference profiles across variants. Tailor features/marketing to specific segments."
        else:
            impact_text = "<b>Business Action Recommendation:</b> No significant association was detected. " \
                          "User distributions are statistically homogeneous across groups. Standardize the layout/offering."

    story.append(Paragraph(decision_text, body_style))
    story.append(Spacer(1, 8))
    story.append(make_callout(
        conclude_box_title,
        impact_text,
        bg_color=conclude_box_color,
        border_color=conclude_box_border
    ))
    story.append(Spacer(1, 10))
    story.append(Paragraph("<b>Plain English:</b>", h2_style))
    story.append(Paragraph(build_plain_english_summary(), body_style))
    
    # Build Document
    doc.build(story, canvasmaker=NumberedCanvas)
